""" Globals with necessary settings """

GLOBAL_LOCKER_CAPACITY = 3
GLOBAL_SHOWER_CAPACITY = 3

GENDER_MALE = 'M'
GENDER_FEMALE = 'F'


LOCKER_TIMEOUT = (0.5, 0.8)
SHOWER_TIMEOUT = (0.5, 0.8)
POOL_TIMEOUT = (0.5, 0.8)
